# Generated by Django 3.2.5 on 2022-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=5, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
